docker-compose-yaml: docker-compose.yml

project: drupal-example

tasks:

environments:
  main:
    routes:
      - node:
          - foobar123.test6.com:
              alternativenames:
                - www.test6.foobar.com
                - api.test6.foobarfoobar.com