docker-compose-yaml: docker-compose.yml

project: drupal-example

tasks:

environments:
  main:
    routes:
      - node:
          - foobarpolina123.test6.amazee.io:
              alternativenames:
                - www.test6.polina-test.amazee.io
                - api.test6.foobarfoobarpolina.amazee.io