docker-compose-yaml: docker-compose.yml

project: drupal-example

tasks:

environments:
  main:
    routes:
      - node:
          - foobarpolina123.test6.amazee.io:
              alternativenames:
                - www.polina-test.test6.amazee.io
                - api.foobarfoobarpolina.test6.amazee.io