docker-compose-yaml: docker-compose.yml

project: drupal-example

tasks:

environments:
  main:
    routes:
      - node:
          - foobarpolina123.test6.com:
              alternativenames:
                - www.test6.foobarpolina.com
                - api.test6.foobarfoobarpolina.com